# Generated by Django 3.1.6 on 2021-06-01 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gradelevel', models.CharField(max_length=30, null=True)),
                ('lrn', models.CharField(max_length=11, null=True)),
                ('name', models.CharField(max_length=30, null=True)),
                ('address', models.CharField(max_length=30, null=True)),
                ('birthday', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('faculty', models.CharField(max_length=11, null=True)),
                ('yearlevel', models.CharField(max_length=30, null=True)),
                ('section', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('age', models.CharField(max_length=11, null=True)),
                ('birthday', models.CharField(max_length=30, null=True)),
                ('address', models.CharField(max_length=30, null=True)),
                ('Occupation1', models.CharField(max_length=30, null=True)),
                ('fathersname', models.CharField(max_length=30, null=True)),
                ('occupation2', models.CharField(max_length=30, null=True)),
                ('mothersname', models.CharField(max_length=30, null=True)),
                ('profile', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Eform.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstchoice', models.CharField(max_length=30, null=True)),
                ('secondchoice', models.CharField(max_length=30, null=True)),
                ('specialz', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Eform.student')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('gradelevel', models.CharField(max_length=30, null=True)),
                ('scheds', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Eform.student')),
            ],
        ),
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportcard', models.FileField(default='', upload_to='')),
                ('psa', models.FileField(default='', upload_to='')),
                ('require', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Eform.student')),
            ],
        ),
        migrations.CreateModel(
            name='ClassShift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cshifts', models.CharField(choices=[('am', 'Morning Shift'), ('pm', 'Afternon Shift')], default='none', max_length=10)),
                ('classshift', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Eform.student')),
            ],
        ),
    ]
