# Generated by Django 3.1.6 on 2021-06-14 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Eform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirements',
            name='psa',
            field=models.FileField(blank=True, default='none', upload_to=''),
        ),
        migrations.AlterField(
            model_name='requirements',
            name='reportcard',
            field=models.FileField(blank=True, default='none', upload_to=''),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='gradelevel',
            field=models.IntegerField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='birthday',
            field=models.IntegerField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gradelevel',
            field=models.IntegerField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='lrn',
            field=models.IntegerField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='age',
            field=models.IntegerField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='birthday',
            field=models.IntegerField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='profile',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Eform.student'),
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
